### ISSUE TITLE
Plugin times out on startup

### ISSUE THREAD

**Issue by nmische** [turbot/steampipe-plugin-kubernetes#118]
**Describe the bug**
Plugin times out on startup when there are several connections with dynamic CRD tables.

```
Warning: failed to start plugin 'hub.steampipe.io/plugins/turbot/kubernetes@latest': timed out waiting for hub.steampipe.io/plugins/turbot/kubernetes@latest to startup after 5 seconds
```

**Steampipe version (`steampipe -v`)**
```
steampipe version 0.18.0
```

**Plugin version (`steampipe plugin list`)**
```
hub.steampipe.io/plugins/turbot/aws@latest 0.95.0
hub.steampipe.io/plugins/turbot/csv@latest 0.5.0
hub.steampipe.io/plugins/turbot/github@latest 0.25.1
hub.steampipe.io/plugins/turbot/kubernetes@latest 0.17.0
```

**To reproduce**
* Configure multiple connections to kubernetes clusters containing several CRDs.
    * In my case I see this when trying to connect to more than 6 clusters running Istio.
* Run a steampipe command: `steampipe plugin list` or `steampipe query` 

**Expected behavior**
All kubernetes connections load.

**Additional context**
Kubernetes clusters in my case are EKS running Istio.

**Comment by e-gineer** [comment]
Can you please try again using the new CLI v0.19.1?

We extended the database timeout in v0.18.1 - https://github.com/turbot/steampipe/blob/main/CHANGELOG.md#v0181-2023-01-18

And made it configurable in v0.19.0 if needed - https://github.com/turbot/steampipe/blob/main/CHANGELOG.md#v0190-2023-03-09

**Comment by nmische** [comment]
That seems to have addressed the issue! Thanks @e-gineer!
