### ISSUE TITLE
Want to hard code credentials directly into "kubernetes plugin spc file" instead of giving absolute path to the kubeconfig file inside the spc file 

### ISSUE THREAD

**Issue by kamilmansoor3901886** [turbot/steampipe-plugin-kubernetes#119]
I am using steampipe tool for kubernetes inventory and compliance. The below is the "kubernetes.spc file" which will be used by steampipe. However instead of giving the path to the "kubeconfig file" under the field "config_path" in the "kubernetes.spc file" , I just simply want to hardcode the credentials(like certificate-authority-data, client-certificate-data, client-key-data) of kubeconfig file in the below spc file. How can i achieve this? What would be the exact format of my spc file. please help
```
connection "kubernetes" {
  plugin = "kubernetes"
   By default, the plugin will use credentials in "~/.kube/config" with the current context.
   OpenID Connect (OIDC) authentication is supported without any extra configuration.
   The kubeconfig path and context can also be specified with the following config arguments:
   Specify the file path to the kubeconfig.
   Can also be set with the "KUBE_CONFIG_PATHS" or "KUBERNETES_MASTER" environment variables.
   config_path = "~/.kube/config"
   Specify a context other than the current one.
   config_context = "minikube"
   If no kubeconfig file can be found, the plugin will attempt to use the service account Kubernetes gives to pods.
   This authentication method is intended for clients that expect to be running inside a pod running on Kubernetes.
}
```
I want to hard code creds directly in spc file from kubeconfig file. Let say i dont have kubeconfig file exist in my system. like in cases of aws we directly mention creds like aws_secret_key, access_key in spc file. I want to achieve same with kubernetes spc file like the below pattern but it is not working.
```
connection "kubernetes" {
  plugin = "kubernetes"
  config = {
    # Hardcoded credentials for Kubernetes API server
    host = "https://your-kubernetes-host/"
    certificate-authority-data = "<certificate-authority-data>"
    client-certificate-data = "<client-certificate-data>"
    client-key-data = "<client-key-data>"
  }
}
```

**Comment by bigdatasourav** [comment]
Hey @kamilmansoor3901886, as of now, hard code credentials in the `.spc` file are not supported; we are evaluating the options and will update you soon.

**Comment by bigdatasourav** [comment]
@kamilmansoor3901886, my apologies for the lack of communication regarding this issue.

We are currently actively addressing the issue you mentioned. We have created a dedicated [branch](https://github.com/turbot/steampipe-plugin-kubernetes/tree/issue-119) with all the necessary changes and updates. While the branch is still a work in progress, we encourage you to test it out to see if it meets your expectations. Your feedback on this branch would be greatly appreciated as it will help us further refine and improve the solution.

To use this branch, you need to follow the below steps - 

- git clone git@github.com:turbot/steampipe-plugin-kubernetes.git
- git checkout issue-119
- make
- run your query

Also, you need to update the config file as below - 
```
connection "kubernetes" {
  plugin = "kubernetes"
  custom_resource_tables = ["*"]
  host = "<scheme://hostname:port>"
  cluster_ca_certificate = "<certificate-authority-data>"
  client_certificate = "<client-certificate-data>"
  client_key = "<client-key-data>"
}

**Comment by bigdatasourav** [comment]
@kamilmansoor3901886 Could you please help us with the below questions as well - 

- Which K8s version are you using?
- Is there any specific reason you do not have a kubeconfig file in your system?

**Comment by cbruno10** [comment]
@kamilmansoor3901886 In addition to @bigdatasourav 's questions above, can you please also include some more details on how you connect to the Kube cluster(s) today, e.g., do you connect from your local laptop, an EC2 instance, a container, and when you do connect, do you pass in the creds using `kubectl` or another tool?

**Comment by cbruno10** [comment]
Closing this issue for now, we may re-open once we're interested in adding Kubernetes plugin support to Steampipe Cloud where this auth method will be better understand and used.
