### ISSUE TITLE
Improve error messaging on connection error or timeout

### ISSUE THREAD

**Issue by nmische** [turbot/steampipe-plugin-kubernetes#120]
**Is your feature request related to a problem? Please describe.**
I manage several dozens connections for the kubernetes plugin. Occasionally one of the clusters behind these connections goes stale (the cluster gets destroyed or rebuilt). When I try to run queries when this happens the steampipe cli returns:

```
Error: failed to start plugin 'hub.steampipe.io/plugins/turbot/kubernetes@latest': timed out waiting for hub.steampipe.io/plugins/turbot/kubernetes@latest to startup after 5 seconds (SQLSTATE HV000)
```
This error gives no information about which connection may have had an error or timedout.

**Describe the solution you'd like**
The above error gives information about connections that failed.

**Describe alternatives you've considered**
I've tried running `steampipe query` with trace logging enabled, but, as far as I can tell, that doesn't seem to report the issue.

**Additional context**

**Comment by cbruno10** [comment]
Hi @nmische , I believe this behaviour will be changing in Steampipe CLI v0.20.0, which should be releasing this week or next. I'll keep this issue open and we can check if the behaviour you reported has improved.

**Comment by cbruno10** [comment]
Hi @nmische , can you please update to the latest Steampipe CLI v0.20.x version and see if you're still running into the same issues? Thanks!

**Comment by bigdatasourav** [comment]
Hey @nmische, We are closing this issue because we have not heard from you. Please feel free to reopen the issue if you want to share or discuss anything.
