### ISSUE TITLE
Add table kubernetes_version

### ISSUE THREAD

**Issue by jacksgt** [turbot/steampipe-plugin-kubernetes#140]
Hi,
thanks for this super cool plugin!

I think it would be useful to add the Kubernetes client and server version as a table, like this:

```
> select * from kubernetes_version;
+-----------+------------+-------------+
| component | version    | revision    |
+-----------+------------+-------------+
| server    | v1.25.6    | 9ec5f337f9f |
| client    | v1.26.1    | deadbeeeeef |
+-----------+------------+-------------+
```

The [Gitlab plugin](https://hub.steampipe.io/plugins/theapsgroup/gitlab) does something similar.

**Comment by misraved** [comment]
Closing this issue since it is blocked on https://github.com/kubernetes/client-go/issues/1274.

We will reopen it once the above issue gets resolved 👍.
