### ISSUE TITLE
Remove deprecated config arg and env vars from the plugin

### ISSUE THREAD

**Issue by bigdatasourav** [turbot/steampipe-plugin-kubernetes#145]
**Is your feature request related to a problem? Please describe.**
The below parameters are deprecated and will be removed after next month.
config_paths (please use config_path instead)
KUBE_CONFIG_PATHS (please use KUBECONFIG or KUBE_CONFIG_PATH instead)
KUBERNETES_MASTER (please use KUBECONFIG or KUBE_CONFIG_PATH instead)

**Comment by cbruno10** [comment]
We should look to remove these in a new version in about 30 days from now to give users a chance to change to the new config arg or env vars

**Comment by misraved** [comment]
Addressed in https://github.com/turbot/steampipe-plugin-kubernetes/commit/eaf655f73cfc97c8a3cd6baab0be50b872fc30bd
