### ISSUE TITLE
Empty returned `data` field in configmap and secret tables

### ISSUE THREAD

**Issue by hileef** [turbot/steampipe-plugin-kubernetes#149]
**Describe the bug**

If I understood the behaviour correctly,  the `data` field ( as in : `kubernetes_config_map.data` and `kubernetes_secret.data` ) is incorrectly overriden, and therefore returned as `nil` due to a bug introduced in #139 

In particular, the issue is that the `Data` field from parsedContent https://github.com/turbot/steampipe-plugin-kubernetes/blob/1367ea2f8e7ac401df959744cd6cad9991eb5dcf/kubernetes/utils.go#L657 

**overrides the `Data` field from the kubernetes API object struct** with a `nil` value,  
which I believe to be unintended behvaiour, in lines such as this one : 
- https://github.com/turbot/steampipe-plugin-kubernetes/blob/1367ea2f8e7ac401df959744cd6cad9991eb5dcf/kubernetes/table_kubernetes_config_map.go#L206
- https://github.com/turbot/steampipe-plugin-kubernetes/blob/1367ea2f8e7ac401df959744cd6cad9991eb5dcf/kubernetes/table_kubernetes_secret.go#L218

I would personally feel more confortable with an implementation that does not mix fields from internal struct with fields from the kubernetes API object structs, but given my limited knowledge of this codebase, for now I will open a hotfix PR that changes the `Data` field's name : see #150 

---

**Steampipe version**
Steampipe v0.20.10

**Plugin version (`steampipe plugin list`)**
Found bug when testing versions : 
-  `hub.steampipe.io/plugins/turbot/kubernetes@0.22`
-  `hub.steampipe.io/plugins/turbot/kubernetes@0.21`

But is _**NOT**_ present in version : `hub.steampipe.io/plugins/turbot/kubernetes@0.20`

**To reproduce**

Run any query attempting to make use of the data field, such as the default one from the documentation : 
```
select
  name,
  namespace,
  data.key,
  data.value,
  age(current_timestamp, creation_timestamp)
from
  kubernetes_config_map,
  jsonb_each(data) as data
order by
  namespace,
  name;
```
The data field is always null.

**Expected behavior**

If the configmap's (or secret) actual data within etcd is not empty, and therefore the API response from kubernetes's data field is not empty, then this plugin should be correctly returning it.

**Additional context**
Hopefully this description contains enough information 🙂

**Comment by misraved** [comment]
Fixed in https://github.com/turbot/steampipe-plugin-kubernetes/pull/150
