### ISSUE TITLE
Using manifest path comes up with multple folders (single file is fine) or YAML comes up with an ERROR: failed to start plugin 'hub.steampipe.io/plugins/turbot/kubernetes@latest': timed out waiting for hub.steampipe.io/plugins/turbot/kubernetes@latest to s

### ISSUE THREAD

**Issue by stuart14** [turbot/steampipe-plugin-kubernetes#162]
**Describe the bug**

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by cbruno10** [comment]
Hi @stuart14 , can you please share what's in your `~/.steampipe/config/kubernetes.spc` file (with sensitive info removed)? Also, can you please share some more details on what your directory/file structure looks like? Thanks!

**Comment by cbruno10** [comment]
Thanks @stuart14 , can you please try restarting Steampipe and then look for any warnings or errors in your `~/.steampipe/logs/plugin-<date>.log`? Sometimes if we fail to load files (thus causing the plugin to fail to load) errors will appear in those logs.

**Comment by stuart14** [comment]
@cbruno10 The same error appears.
2023-09-22 14:38:35.118 UTC [WARN]  timed out waiting for hub.steampipe.io/plugins/turbot/kubernetes@latest to startup after 20 seconds

**Comment by graza-io** [comment]
I hit a similar issue today albeit I was able to successfully query multiple folders in `manifest_file_paths` - I received the issue when attempting to define a connection with `helm` and `manifest` definitions combined.

### Multiple Manifest Paths - Working

Connection:
```hcl
connection "old_code_mani" {
  plugin = "kubernetes"
  manifest_file_paths = [
    "/Users/graza/src/turbot/steampipe-plugin-kubernetes/test-files/**/*.y*ml",
    "/Users/graza/src/turbot/steampipe-plugin-kubernetes/k8s-test/**/*.yaml"
    ]
  source_type = "all"
}
```

Query/Result:
```
> select name, source_type from old_code_mani.kubernetes_service
+---------------------------+-------------+
| name                      | source_type |
+---------------------------+-------------+
| my-nginx-svc              | manifest    |
| jenkins                   | manifest    |
| nginx                     | manifest    |
| metrics-server            | deployed    |
| dashboard-metrics-scraper | deployed    |
| kubernetes                | deployed    |
| kube-dns                  | deployed    |
| kubernetes-dashboard      | deployed    |
+---------------------------+-------------+
```

### Helm - Working

Connection:
```hcl
connection "old_code_helm" {
  plugin = "kubernetes"
  custom_resource_tables = ["*"]
  helm_rendered_charts = {
    "yyy-helm" = {
      chart_path        = "/Users/graza/src/xxx/infrastructure/k8s/yyy-helm"
      values_file_paths = ["/Users/graza/src/xxx/infrastructure/k8s/clusters/zzz/zzz-values.yaml"]
    }
  }
  source_type = "all"
}
```

Query/Result:
```
> select name, source_type from old_code_helm.kubernetes_namespace
+--------------------------+------------------------+
| name                     | source_type            |
+--------------------------+------------------------+
| cert-manager             | helm_rendered:yyy-helm |
| reflector                | helm_rendered:yyy-helm |
| prometheus-abcd1-0001-aa | helm_rendered:yyy-helm |
| ingress-nginx-main       | helm_rendered:yyy-helm |
| my-redis                 | helm_rendered:yyy-helm |
| prometheus-remote        | helm_rendered:yyy-helm |
| steampipe-cloud          | helm_rendered:yyy-helm |
| mimir                    | helm_rendered:yyy-helm |
| vault                    | helm_rendered:yyy-helm |
| temporal                 | helm_rendered:yyy-helm |
| elasticsearch            | helm_rendered:yyy-helm |
| redpanda-v2              | helm_rendered:yyy-helm |
| kube-public              | deployed               |
| kubernetes-dashboard     | deployed               |
| default                  | deployed               |
| kube-system              | deployed               |
| kube-node-lease          | deployed               |
+--------------------------+------------------------+
```

### Amalgamated - Fails

Connection: 
```hcl
connection "old_code_all" {
  plugin = "kubernetes"
  custom_resource_tables = ["*"]
  manifest_file_paths = [
    "/Users/graza/src/turbot/steampipe-plugin-kubernetes/test-files/**/*.y*ml",
    "/Users/graza/src/turbot/steampipe-plugin-kubernetes/k8s-test/**/*.yaml"
    ]
  helm_rendered_charts = {
    "yyy-helm" = {
      chart_path        = "/Users/graza/src/xxx/infrastructure/k8s/yyy-helm"
      values_file_paths = ["/Users/graza/src/xxx/infrastructure/k8s/clusters/zzz/zzz-values.yaml"]
    }
  }
  source_type = "all"
}
```

Query/Result:
```
> .inspect old_code_all
+--------------+---------------------------------------------------+-------------+-------+------------------------+---------------------------+
| connection   | plugin                                            | schema mode | state | error                  | state updated             |
+--------------+---------------------------------------------------+-------------+-------+------------------------+---------------------------+
| old_code_all | hub.steampipe.io/plugins/turbot/kubernetes@latest |             | error | plugin failed to start | 2023-09-29T16:38:16+01:00 |
+--------------+---------------------------------------------------+-------------+-------+------------------------+---------------------------+
> select * from old_code_all.kubernetes_namespace
Error: connection old_code_all failed to load: plugin failed to start
```

Relevant plugin log entry:
```
2023-09-29 15:38:16.244 UTC [WARN]  timed out waiting for hub.steampipe.io/plugins/turbot/kubernetes@latest to startup after 20 seconds
```

**Comment by stuart14** [comment]
@cbruno10 @graza-io yes I have reproduced this and the plugin works fine with a single folder and *yml it does not like a large number of folders where is has to recursively query / audit and times out with a error.

**Comment by graza-io** [comment]
Just to give an update on this, have been doing some more digging and hope to have a further update shortly.

**Comment by stuart14** [comment]
@graza-io Thanks unfortunately, I upgraded and recived the same error :(

**Comment by LalitLab** [comment]
@graza-io 
I have installed the latest plugin today and still facing the same error.
Plugin kubernetes - `v0.25.0`
Steamppe cli  - `0.20.11`

my connection config(The one that got created by installation of plugin - I have removed commented stuff for clarity):
```hcl
connection "kubernetes" {
  plugin = "kubernetes"

  # Defaults to all custom resources
  custom_resource_tables = ["*"]
}
```

I expected it to pick `current-context` and list out the resources for same.

![image](https://github.com/turbot/steampipe-plugin-kubernetes/assets/37527306/09008a87-5138-46b1-804e-ee278a019d75)

![image](https://github.com/turbot/steampipe-plugin-kubernetes/assets/37527306/148474ff-00d7-41f6-b7e6-f05c060f90d0)

I think by default the plugin shouldn't look for the manifest files.
Thank you

**Comment by graza-io** [comment]
@stuart14 - can you confirm that there were no dangling `steampipe` processes running which may have kept the older plugin version as the active one - as I literally can quadruple the number of manifest files / helm charts I'm looking at in the new version without hitting this timeout.

**Comment by graza-io** [comment]
@cbruno10 thoughts on the comment raised by @LalitLab?
Current default is essentially `["deployed", "helm", "manifest"]` for context.

Options:
- Set default to reduced list (unsure what preference would be here)
- By default have `manifest_file_paths` uncommented and set to `[]`
- Adjust the code so that if `manifest_file_paths` is not set we default it to an empty array instead of returning an error

@LalitLab - also thanks for bringing this to our attention.

**Comment by stuart14** [comment]
> @stuart14 - can you confirm that there were no dangling `steampipe` processes running which may have kept the older plugin version as the active one - as I literally can quadruple the number of manifest files / helm charts I'm looking at in the new version without hitting this timeout.

@cbruno10 No process running - can you confirm then limit on folders and minifests and in real world assessment (which i am running) you could be looking at 1000's of YAML manifests

**Comment by graza-io** [comment]
Hm, I don't think we've looked at 1000s of files in a single connection..

One approach you could take is to separate the file loads into various connections and then use an aggregator across those connections, [this section](https://hub.steampipe.io/plugins/turbot/kubernetes#multiple-context-connections) of the documentation gives an example of this for numerous `contexts` but same approach can be applied to groups/collections of `manifest` file based connections.

**Comment by graza-io** [comment]
@stuart14 I wasn't suggesting adding of `contexts` merely that you can setup a connection per logical grouping of manifest files and then utilise an aggregator to query against all at the same time.

Let me give a quick example
`kubernetes.spc`
```hcl
connection "all_k8s" {
  type        = "aggregator"
  plugin      = "kubernetes"
  connections = ["k8s_man_*"]
}

connection "k8s_man_a" {
  plugin = "kubernetes"
  manifest_file_paths = [ "/path/to/app_a/**/*.yaml", "/path/to/app_a/**/*.yml" ]
  source_types = ["manifest"]
}

connection "k8s_man_b" {
  plugin = "kubernetes"
  manifest_file_paths = [ "/path/to/app_b/**/*.yaml", "/path/to/app_b/**/*.yml" ]
  source_types = ["manifest"]
}

connection "k8s_man_c" {
  plugin = "kubernetes"
  manifest_file_paths = [ "/path/to/app_c/**/*.yaml", "/path/to/app_c/**/*.yml" ]
  source_types = ["manifest"]
}
```

Since my aggregator is alphabetically first, I don't need to specify it as a qualifier(prefix) but I will in this example so it's clear.

```sql
select * from all_k8s.kubernetes_service;
```

Will return all services in all `manifest` files in:
- `/path/to/app_a` (& all it's sub-directories)
- `/path/to/app_b` (& all it's sub-directories)
- `/path/to/app_c` (& all it's sub-directories)

The end result of this would be that your aggregator should display everything as if it was a single connection looking at all the different locations for manifest files.

Hope this provides more clarity.

**Comment by bigdatasourav** [comment]
Hey, @stuart14, we're closing this issue as we have not heard back from you; please feel free to re-open if you want to share anything. We will investigate it further. Thanks!
