### ISSUE TITLE
Add table kubernetes_deployment_config

### ISSUE THREAD

**Issue by khushboo9024** [turbot/steampipe-plugin-kubernetes#168]
**References**
Add any related links that will help us understand the resource, including vendor documentation, related Kubernetes issues, and Go SDK documentation.

**Comment by Subhajit97** [comment]
Kubernetes (K8s) does not have a built-in resource kind called `DeploymentConfig`. The concept of `DeploymentConfig` is not a native Kubernetes resource; it is specific to OpenShift, which is an extended container platform built on top of Kubernetes.

In OpenShift, the DeploymentConfig is used as a higher-level abstraction for deploying applications and managing their lifecycle. It provides capabilities similar to Kubernetes Deployments but with additional features like rolling deployments and hooks.

We already have a table in our [Openshift plugin](https://hub.steampipe.io/plugins/turbot/openshift/tables/openshift_deployment_config).

**Comment by rajlearner17** [comment]
Thanks @Subhajit97 
Marking this closed for now
