### ISSUE TITLE
add annotations column on all CRD resources

### ISSUE THREAD

**Issue by seiyar81** [turbot/steampipe-plugin-kubernetes#195]
**Is your feature request related to a problem? Please describe.**
First of all: awesome tool and plugin ! We've been using Steampipe with the Kubernetes plugin to design some customs dashboards for FluxCD and it is just perfect !!
Maybe my question/request is dumb so feel free to tell me :smile: 
I'm currently trying to design a custom Traefik dashboard and I need to access annotations for the IngressRoute CRD.

**Describe the solution you'd like**
Could annotations be added for all CRD resources [here](https://github.com/turbot/steampipe-plugin-kubernetes/blob/main/kubernetes/common_columns.go#L88) just as the labels are ?

**Describe alternatives you've considered**
Otherwise I should make a PR with the Traefik (and all other CRD I use), maybe overkill and not wanted.

**Additional context**
NA.

**Comment by ParthaI** [comment]
Hello @seiyar81, I have raised a [PR](https://github.com/turbot/steampipe-plugin-kubernetes/pull/202) by adding a common column to the Custom Resource tables. It would be great if you could try it in the PR branch `issue-195` and let us know your feedback.

Steps for querying the custom resource tables from the branch `issue-195`:

- git clone https://github.com/turbot/steampipe-plugin-kubernetes.git
- cd steampipe-plugin-kubernetes
- git checkout `issue-195`
- run `make`
- Run the query for custom resources

If you need anything else, please let us know.

Thanks you!

**Comment by seiyar81** [comment]
Hello @ParthaI !
Thanks you very much for your very quick support on this request, it works like a charm !!

**Comment by sebastianwebber** [comment]
@ParthaI the PR is not working for me. Please see:

```bash
$ steampipe query
Welcome to Steampipe v0.21.2
For more information, type .help

> select name, resource_annotations from conn_example.kubernetes_mycrd where namespace = 'foo';
+------------+----------------------+
| name       | resource_annotations |
+------------+----------------------+
| bar        | <null>               |
+------------+----------------------+
>

$ k get mycrd/bar -o json | jq '.metadata.annotations' | wc -l
      10
```

I've redacted some values. Let me know if you need more info.

**Comment by ParthaI** [comment]
@sebastianwebber, we appreciate your valuable feedback on Steampipe!

- We've introduced a common column for CRD resources called [annotations](https://github.com/turbot/steampipe-plugin-kubernetes/pull/202/files#diff-0731bc508e7e1a7fda3fb7ff1b5c3fe2c4e24cd9d12e7b58fe621321264a2767R91) (this column will be present for each custom resource), not the column `resource_annotations`.
- All annotations associated with a custom resource will now be populated in the `annotations` column.
- Kindly attempt to retrieve the value of the `annotations` column for the custom resource.
- If you encounter any issues or are unable to fetch the annotation value, could you please share the configuration file for the Kubernetes plugin located in `~/.steampipe/config/kubernetes.spc`. Additionally, provide the `*.yml` file for the specific custom resource and its custom resource definition file? (This will help us dig into the issue more)

**_Kindly ensure that any sensitive information is redacted before sharing._**

Thank You!
