### ISSUE TITLE
The plugin not support Auth Provider OIDC

### ISSUE THREAD

**Issue by filipponova** [turbot/steampipe-plugin-kubernetes#26]
**Describe the bug**
To connect me to my k8s clusters using kubectl use or OIDC authentication provider, but it looks like the plugin doesn't support it. When trying to run as queries I just got an error message `[2021-08-18 17:43:19] [HV000] ERROR: rpc error: code = Unknown desc = no authentication provider found for name "oidc"`.

**Steampipe version (`steampipe -v`)**
v0.7.2

**Plugin version (`steampipe plugin list`)**
v0.0.2

**To reproduce**
Need to have OIDC authentication provider configured on your k8s clusters. After that just try running any queries.

**Expected behavior**
Normal execution of queries and use of auth providers.

**Additional context**
N/A

**Comment by johnsmyth** [comment]
@filipponova - To confirm, you want to connect using steampipe on your local machine (from outside the k8s cluster) using steampipe, using an OIDC auth mechanism that works with kubectl, correct?  Also curious - is this an on-prem cluster or hosted in a cloud provider somewhere?  Which OIDC provider are you using?

**Comment by filipponova** [comment]
@johnsmyth , Hello. Yes, I am on my local machine running steampipe to access my AWS hosted k8s clusters. My OIDC provider is Keycloak. I can run kubectl from my local machine, but when I run it via steampipe I get the error I reported.

```
Last login: Thu Aug 19 14:20:16 on ttys000
➜  ~ kubectl get nodes

NAME                           STATUS   ROLES                     AGE      VERSION
ip-XXXX.ec2.internal   Ready    node,spot-worker    33m     v1.17.17
ip-XXXX.ec2.internal   Ready    master                       93d     v1.17.17
ip-XXXX.ec2.internal   Ready    node                          34d     v1.17.17
ip-XXXX.ec2.internal   Ready    node,spot-worker    8d        v1.17.17
ip-XXXX.ec2.internal   Ready    node,spot-worker    8d        v1.17.17

```

**Comment by rajlearner17** [comment]
@filipponova we have provided a fix for this issue. This is merged to main. Can you pls test this out to see if your  k8s clusters configured with OIDC auth working?

- Clone repo by  -` git clone  https://github.com/turbot/steampipe-plugin-kubernetes.git`
- `cd <steampipe-plugin-kubernetes> ` (Plugin folder)
- Execute `make`

Hope the above generic steps allow to build the plugin, if not let us know. This is expected to release today.

**Comment by mynameiswhm** [comment]
I've checked the fix on Kubernetes clusters that use [Dex](https://dexidp.io/) or [Hydra](https://www.ory.sh/hydra/) — works great now! Thanks!

**Comment by filipponova** [comment]
Hi Guys, in my tests i have success! Thank you so much! :
