### ISSUE TITLE
Add table kubernetes_storage_class

### ISSUE THREAD

**Issue by nmische** [turbot/steampipe-plugin-kubernetes#72]
**References**

* https://kubernetes.io/docs/concepts/storage/storage-classes/

**Comment by bigdatasourav** [comment]
@nmische Thank you for using Steampipe and raising this issue with us. We will look into it.

**Comment by misraved** [comment]
@nmische, we did some research in the Go SDK for Kubernetes and we managed to find out the corresponding `list` and `get` calls for `Storage Class`.

https://pkg.go.dev/k8s.io/client-go/kubernetes/typed/storage/v1#StorageClassInterface.List
https://pkg.go.dev/k8s.io/client-go/kubernetes/typed/storage/v1#StorageClassInterface.Get

Would you like to contribute by creating this table? It would definitely be an amazing addition 👍 .
