### ISSUE TITLE
Support InClusterConfig for Kubernetes

### ISSUE THREAD

**Issue by taliesins** [turbot/steampipe-plugin-kubernetes#81]
**Is your feature request related to a problem? Please describe.**
We run steampipe dashboards inside a container. We would like to not have to configure a KubeConfig file and rather really on "/var/run/secrets/kubernetes.io/serviceaccount/token". In KubeCtl the method is called InClusterConfig.

**Describe the solution you'd like**
Add InClusterConfig support. 

**Describe alternatives you've considered**
Attempted to create Kube config from existing information dynamically.

**Additional context**
Link to InClusterConfig method
https://github.com/kubernetes/client-go/blob/fcdf37233b57445e4a6a4038ec580e9aaac931de/rest/config.go#L274

**Comment by bigdatasourav** [comment]
Hey @taliesins, Thank you for using Steampipe and raising this issue with us. We will look into it.

**Comment by cbruno10** [comment]
Not stale, work is still in progress.

**Comment by taliesins** [comment]
Thanks very much guys! Great job. We will give it a go in our steampipe container.
