### ISSUE TITLE
Honor ClientConfigLoadingRules 

### ISSUE THREAD

**Issue by mrkwtz** [turbot/steampipe-plugin-kubernetes#90]
**Describe the bug**
To be fair I don't know if it's working as intended or a bug, but here we go. 

The plugin doesn't seem to use the ClientConfigLoadingRules provided by the k8s client-go sdk. So for example setting the KUBECONFIG env doesn't lead to the plugin using the path provided in the value of the env to build the client config. That's unfortunate because all other Kubernetes CLIs that we use work with the KUBECONFIG env. 

I guess that because here https://github.com/turbot/steampipe-plugin-kubernetes/blob/main/kubernetes/utils.go#L184 a default config path is set and here https://github.com/turbot/steampipe-plugin-kubernetes/blob/main/kubernetes/utils.go#L209-L213 if configPaths has one or multiple entries they are configured with precedence or explicit. In the default case it's set explicit which leads to the plugin not trying any other location for the Kubernetes config at all.

I know there is KUBE_CONFIG_PATHS variable but why introduce a new one when there might be already an env set with the desired value (KUBECONFIG).

I didn't test it but removing the default config path from the code may resolve all the above mentioned problems. 

**Steampipe version (`steampipe -v`)**
Example: v0.16.4

**Plugin version (`steampipe plugin list`)**
Example: v0.12.0

**To reproduce**
Set KUBECONFIG env to something else than the default value (~/.kube/config)

**Expected behavior**
The envs which are used across almost all Kubernetes CLIs should be usable in the plugin.

**Comment by misraved** [comment]
Welcome to Steampipe @mrkwtz, great to see you using the plugin 👍 .

Fantastic to see you getting your hands dirty with the code 😄 . 

Currently, we definitely don't support the use of the `KUBECONFIG` env variable(which should be a feature request/enhancement). 

```
I didn't test it but removing the default config path from the code may resolve all the above mentioned problems.
```

Would be great if you could test out the above fix 👍 or raise a PR for adding the support for the environment variable 😄 .

**Comment by mrkwtz** [comment]
Thanks @misraved 
It's the first PR #92 I've ever submitted so pleas go easy on me, if there is something I need to do additionally please let me know

**Comment by cbruno10** [comment]
Hi @mrkwtz , happy new year!

After this issue was tagged as stale, I took a look at the open PR and found this [comment](https://github.com/turbot/steampipe-plugin-kubernetes/pull/92#discussion_r1016781767) from a few weeks ago. When you get a chance, can you please see if you can find that info, which will help us further review the PR?

Thanks!

**Comment by cbruno10** [comment]
Re-opening so this issue will be included in the upcoming issue review
