### ISSUE TITLE
Handle not found error in kubernetes_ingress table

### ISSUE THREAD

**Issue by bigdatasourav** [turbot/steampipe-plugin-kubernetes#91]
**Describe the bug**
> select * from kubernetes_ingress

Error: the server could not find the requested resource (get ingresses.extensions) (SQLSTATE HV000)

**Comment by ngirard** [comment]
Hi,
I'm affected by the same defect:
```
steampipe query '
   select
      schedule as "Schedule",
      active as "Active",
      suspend as "Suspend",
      concurrency_policy as "Concurrency Policy",
      last_schedule_time as "Last Schedule Time",
      last_successful_time as "Last Successful Time",
      successful_jobs_history_limit as "Successful Jobs History Limit",
      failed_jobs_history_limit as "Failed Jobs History Limit"
    from
      kubernetes_cronjob;
'

Error: the server could not find the requested resource (SQLSTATE HV000)
```

Is there anything I can do to help ?

Cheers, and thanks for the good work !

**Comment by bigdatasourav** [comment]
@ngirard Thanks for checking this out. We have a [PR](https://github.com/turbot/steampipe-plugin-kubernetes/pull/98) in the queue to be released with ETA this weekend; I would request you to try it.
