### ISSUE TITLE
Dynamic CRD table creation fails when a dynamic column conflicts with common column

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe-plugin-kubernetes#96]
**Describe the bug**
Dynamic CRD table creation fails when a dynamic column conflicts with a common column, which are defined in https://github.com/turbot/steampipe-plugin-kubernetes/blob/1639ee7bdad60bdc63633a56cb91ffb32b3d4ab2/kubernetes/common_columns.go#L83-L96

**Steampipe version (`steampipe -v`)**
v0.18.0-dev.10

**Plugin version (`steampipe plugin list`)**
v0.13.0

**To reproduce**
Create a custom resource definition and object with the property `labels` and then start Steampipe.

**Expected behavior**
All dynamic columns should be created alongside the common columns.

**Additional context**

**Comment by cbruno10** [comment]
Possible solutions to resolve conflicts (from @e-gineer ):

Options:
- Move common columns into a JSONB `metadata` (or similar name) column.
- Rename ALL common columns to have a standard prefix (e.g. `_` or `metadata_` )
- Rename CONFLICTING common columns to have a standard prefix (e.g. `_` or `metadata_` )
- Rename CONFLICTING columns created by the CRD to have a prefix (e.g. `spec_` )
-  (I don't think we should rename ALL columns defined by the CRD, so excluding that option)

**Comment by nmische** [comment]
Any update here? I would really like to be able to query for custom Istio resources.

**Comment by cbruno10** [comment]
Hi @nmische , we don't have an update yet for this plugin, as we've temporarily put this work on hold, as we're not ready to merge in the dynamic tables for CRDs, due to aggregator connections not working with them (please see https://github.com/turbot/steampipe-plugin-kubernetes/issues/97#issuecomment-1356980022 for more details).

In the meantime, one workaround is you can locally build the plugin from the `crd-table-doc` branch. Before building, in the CRD common columns definition function, you can rename/remove any common columns that are causing issues (https://github.com/turbot/steampipe-plugin-kubernetes/blob/crd-table-doc/kubernetes/common_columns.go#L83-L96).
