### ISSUE TITLE
Dynamic CRD table creation fails when using an aggregator connection

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe-plugin-kubernetes#97]
**Describe the bug**
Dynamic CRD table creation fails when using an aggregator connection

**Steampipe version (`steampipe -v`)**
v0.18.0-dev.10

**Plugin version (`steampipe plugin list`)**
v0.13.0

**To reproduce**
Create 2 connections in `kubernetes.spc`, and then create 1 aggregator connection using both of the aforementioned connections.

**Expected behavior**
Aggregator connections should work correctly.

**Additional context**

**Comment by nmische** [comment]
How does this fail? Is this a broader steampipe issue, or specific to this plugin?

**Comment by cbruno10** [comment]
@nmische This is a broader Steampipe issue, I've opened https://github.com/turbot/steampipe/issues/2886 for tracking. So because of that bug, we're holding off on adding dynamic CRDs to this Kubernetes plugin for now, as we don't want to break any existing aggregator connections in this plugin. Unfortunately, even if the users don't intend to use CRDs, the way we generate dynamic tables in the schema on plugin initialization, this would result in plugin initialization failure.
